In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

from tensorflow.keras import layers

In [2]:
tf.__version__

'2.7.0'

In [3]:
dataset_url = 'http://storage.googleapis.com/download.tensorflow.org/data/petfinder-mini.zip'
csv_file = 'datasets/petfinder-mini/petfinder-mini.csv'

tf.keras.utils.get_file('petfinder_mini.zip', dataset_url,
                        extract=True, cache_dir='.')
df = pd.read_csv(csv_file)

In [4]:
df.head()

Type  Age                Breed1  Gender Color1    Color2 MaturitySize  \
0  Cat    3                 Tabby    Male  Black     White        Small   
1  Cat    1  Domestic Medium Hair    Male  Black     Brown       Medium   
2  Dog    1           Mixed Breed    Male  Brown     White       Medium   
3  Dog    4           Mixed Breed  Female  Black     Brown       Medium   
4  Dog    1           Mixed Breed    Male  Black  No Color       Medium   

  FurLength Vaccinated Sterilized   Health  Fee  \
0     Short         No         No  Healthy  100   
1    Medium   Not Sure   Not Sure  Healthy    0   
2    Medium        Yes         No  Healthy    0   
3     Short        Yes         No  Healthy  150   
4     Short         No         No  Healthy    0   

                                         Description  PhotoAmt  AdoptionSpeed  
0  Nibble is a 3+ month old ball of cuteness. He ...         1              2  
1  I just found it alone yesterday near my apartm...         2              0  
2  Their pregnant mother was dumped by her irresp...         7              3  
3  Good guard dog, very alert, active, obedience ...         8              2  
4  This handsome yet cute boy is up for adoption....         3              2

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11537 entries, 0 to 11536
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Type           11537 non-null  object
 1   Age            11537 non-null  int64 
 2   Breed1         11537 non-null  object
 3   Gender         11537 non-null  object
 4   Color1         11537 non-null  object
 5   Color2         11537 non-null  object
 6   MaturitySize   11537 non-null  object
 7   FurLength      11537 non-null  object
 8   Vaccinated     11537 non-null  object
 9   Sterilized     11537 non-null  object
 10  Health         11537 non-null  object
 11  Fee            11537 non-null  int64 
 12  Description    11528 non-null  object
 13  PhotoAmt       11537 non-null  int64 
 14  AdoptionSpeed  11537 non-null  int64 
dtypes: int64(4), object(11)
memory usage: 1.3+ MB


In [6]:
df['target'] = np.where(df['AdoptionSpeed']==4, 0, 1)
df = df.drop(columns=['AdoptionSpeed', 'Description'])

In [7]:
df.sample(frac=1)

Type  Age               Breed1  Gender Color1    Color2 MaturitySize  \
4258  Cat   20  Domestic Short Hair  Female  White  No Color       Medium   
8974  Dog    4               Beagle  Female  Brown  No Color       Medium   
3401  Dog   12          Mixed Breed  Female  Black    Golden       Medium   
6177  Dog    2   Labrador Retriever    Male  Brown    Golden        Large   
7510  Dog    3          Mixed Breed  Female  Black     Brown       Medium   
...   ...  ...                  ...     ...    ...       ...          ...   
8669  Cat    9              Persian  Female  Black     Brown       Medium   
4706  Dog   24          Mixed Breed  Female  Brown  No Color        Small   
4211  Dog    2          Mixed Breed  Female  Black     Brown       Medium   
7815  Dog    2          Mixed Breed    Male  Black     White       Medium   
4105  Dog    5          Mixed Breed    Male  Black     White        Large   

     FurLength Vaccinated Sterilized   Health  Fee  PhotoAmt  target  
4258     Short         No        Yes  Healthy    0         3       1  
8974     Short        Yes   Not Sure  Healthy  120         8       1  
3401    Medium        Yes        Yes  Healthy  100         5       1  
6177    Medium        Yes         No  Healthy    0         5       1  
7510     Short        Yes         No  Healthy    0         2       1  
...        ...        ...        ...      ...  ...       ...     ...  
8669    Medium         No         No  Healthy    0         2       1  
4706     Short         No         No  Healthy    0         0       0  
4211     Short        Yes        Yes  Healthy    0        13       0  
7815    Medium         No         No  Healthy    0         5       1  
4105    Medium        Yes        Yes  Healthy    0         6       1  

[11537 rows x 14 columns]

In [8]:
train, val, test = np.split(df.sample(frac=1), [int(0.8*len(df)), int(0.9*len(df))])

In [9]:
print(len(train), 'training examples')
print(len(val), 'validation examples')
print(len(test), 'test examples')

9229 training examples
1154 validation examples
1154 test examples


In [10]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
dataset = dataset.map(lambda x: x*2)
list(dataset.as_numpy_iterator())

Metal device set to: Apple M1 Pro


2022-01-18 17:03:55.412921: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-01-18 17:03:55.413278: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2022-01-18 17:03:55.442161: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


[2, 4, 6]

In [11]:
df = pd.DataFrame({'species': ['bear', 'bear', 'marsupial'],
                  'population': [1864, 22000, 80000]},
                  index=['panda', 'polar', 'koala'])
for label, content in df.items():
    print(f'label: {label}')
    print(f'content: {content[:,tf.newaxis]}')
    print(content[2])

label: species
content: [['bear']
 ['bear']
 ['marsupial']]
marsupial
label: population
content: [[ 1864]
 [22000]
 [80000]]
80000


/var/folders/4g/vjzzkfln4_qd_3rx25czvzv40000gn/T/ipykernel_4933/1009312421.py:6: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  print(f'content: {content[:,tf.newaxis]}')


In [31]:
df.Age[:,tf.newaxis]

/var/folders/4g/vjzzkfln4_qd_3rx25czvzv40000gn/T/ipykernel_19572/202132281.py:1: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df.Age[:,tf.newaxis]


array([[3],
       [1],
       [1],
       ...,
       [6],
       [9],
       [1]])

In [16]:
df.items?


## TESTING

In [11]:
np.shape([[1,1]])

(1, 2)

In [63]:
x

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [66]:
x = np.arange(8.0)
a,b,c = np.split(x, [3, 5])
print(a)
print(b)
print(c)

[0. 1. 2.]
[3. 4.]
[5. 6. 7.]
